# Generated by Django 5.1.5 on 2025-11-15 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Will Tremlett', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(help_text='Your director bio.')),
                ('hero_image', models.ImageField(blank=True, help_text='Upload a hero/portrait image (stored via Cloudinary).', null=True, upload_to='willtremlett/hero/')),
                ('mailchimp_embed_code', models.TextField(blank=True, help_text='Paste your Mailchimp form embed HTML here.')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='YearTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text="Optional display label, e.g. '2024', '2023–2020'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear higher in the list.')),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Press, General, Agent', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='portfolio.sitesettings')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_length', models.CharField(help_text="e.g. '12 min', 'Feature – 90 min', 'TV episode'", max_length=100)),
                ('role', models.CharField(help_text='e.g. Director, Producer, Editor', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video_embed_url', models.URLField(blank=True, help_text='YouTube/Vimeo URL – we’ll embed it via iframe.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within the year.')),
                ('year_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.yeartab')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
