# Generated by Django 5.1.5 on 2025-11-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Project still/poster image (Cloudinary).', null=True, upload_to='willtremlett/projects/'),
        ),
        migrations.AlterField(
            model_name='contactmethod',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(help_text='Director, Producer, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='video_embed_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube or Vimeo embed URL.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bio',
            field=models.TextField(help_text='Your director biography.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Upload a hero image (stored via Cloudinary).', null=True, upload_to='willtremlett/hero/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='mailchimp_embed_code',
            field=models.TextField(blank=True, help_text='Paste your Mailchimp form HTML embed code here.'),
        ),
        migrations.AlterField(
            model_name='yeartab',
            name='label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='yeartab',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
